### ISSUE TITLE
make install error

### ISSUE THREAD

**Issue by don1001** [0x00pf/STAN#1]
interesting project I'd like to test it but during installation

**./configure; make; make install** I get an error:
```
/usr/bin/install: cannot create regular file '/usr/local/lib/libstan.so.0.0.0': Permission denied
```
even if I run installation with sudo

**Comment by 0x00pf** [comment]
Thanks for your interest in the project

You need to install it as root or use sudo (I will update the readme thanks)
Otherwise provide a --prefix

./configure --prefix=/yourfolder

However note that you need to add the /yourfolder/bin to the path and your/folder/lib to either, your LD_LIBRARY_PATH env variable or /etc/ld.so.conf.

**Comment by bl33pbl0p** [comment]
setting /usr/local as the default prefix should be nice, and /usr/local/lib for the library. They're meant for programs installed outside of the package manager, manually. Then PREFIX can also be passed during build time if the user wants to install to some other path, with the library path still defaulting to ${PREFIX}/lib
